{% set name = "hatch-fancy-pypi-readme" %}
{% set version = "22.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_fancy_pypi_readme-{{ version }}.tar.gz
  sha256: da91282ca09601c18aded8e378daf8b578c70214866f0971156ee9bb9ce6c26a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - hatch-fancy-pypi-readme=hatch_fancy_pypi_readme.__main__:main

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - hatchling
    - python >=3.7
    - tomli
    - typing-extensions

test:
  source_files:
    - AUTHORS.md
    - CHANGELOG.md
    - LICENSE.txt
    - pyproject.toml
    - README.md
    - src
    - tests
  imports:
    - hatch_fancy_pypi_readme
  commands:
    - pip check
    - hatch-fancy-pypi-readme --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - python-build
    - pip
    - pytest

about:
  home: https://github.com/hynek/hatch-fancy-pypi-readme
  summary: Fancy PyPI READMEs with Hatch
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
